version: '3.7'

services:
  redis:
    image: redis:6.2.3
    ports:
      - '6379'
  mock-api:
    build: ./cypress/mock-api
    ports:
      - '3001'
  web:
    image: $LOCAL_IMAGE_ID
    environment:
      NODE_ENV: 'development'
      API_KEYS: '?name=devClient&apiKey=1234&scope=write&scope=read'
      SESSION_USE_REDIS: 'false'
      SERVICE_PUBLISH: '/kursinfoadmin/kurs-pm-data'
      SERVER_PORT: '3000'
      SESSION_SECRET: '1234'
      SESSION_KEY: 'kurs-pm-data-admin-web.pid'
      LOGGING_LEVEL: 'error'
      LOG_LEVEL: 'error'
      LOGGING_ACCESS_LOG: 'false'
      KURS_PM_DATA_API_URI: 'http://mock-api:3001/kurs-pm'
      KURS_PM_DATA_API_KEY: 'secretpassword'
      KURS_INFO_API_URI: 'http://mock-api:3001/kursinfo'
      KURS_INFO_API_KEY: 'secretpassword'
      KURSPLAN_API_URI: 'http://mock-api:3001/kursplan'
      KURSPLAN_API_KEY: 'secretpassword'
      REDIS_URI: 'redis://redis:6379/'
      UG_REDIS_URI: 'redis://redis:6379/'
      KOPPS_URI: 'http://mock-api:3001/kopps/'
      CM_HOST_URL: 'http://mock-api:3001/cm/'
      OIDC_APPLICATION_ID: 'oidcid'
      OIDC_CLIENT_SECRET: 'oidcsecret'
      OIDC_TOKEN_SECRET: 'oidctoken'
    ports:
      - '3000'
    depends_on:
      - redis
      - mock-api

  cypress:
    build: ./cypress
    environment:
      - CYPRESS_baseUrl=http://web:3000/kursinfoadmin/kurs-pm-data/
    depends_on:
      - web
